### ISSUE TITLE
JavaScript dilini öyrənmək üçün qaynaqlar

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Tahir2022/PragmatechFoundationProject#17]
İngilis dilini bilib-bilmədiyinizi bilmirəm deyə daha çox türk və öz dilimizdə qaynaqlar paylaşacam.

- **[Birinci qaynaq](https://javascript.info)**
- **[İkinci qaynaq](https://youtube.com/playlist?list=PLY20HpFruiK12kqke7T5OQVu1BK2ELQL8)**
- **[Üçüncü qaynaq](https://youtube.com/playlist?list=PL7bLjTyftIKBrldcJH9Q3igsYEDuLKp1Q)**
- **[Dördüncü qaynaq](https://youtube.com/playlist?list=PL-Hkw4CrSVq-lamHDwl1J1oI4nwCYYW30)**
- **[Beşinci qaynaq](https://youtube.com/playlist?list=PLpC5j0Gzwvc05KlEfv_Bh0e1LIY6APyCz)**
- **[Altıncı qaynaq](https://developer.mozilla.org/en-US/docs/Web/JavaScript)**
- **[Yeddinci qaynaq](https://www.w3schools.com/js)**

**Comment by Tahir2022** [comment]
İngiliscə advanced səviyyədə bilirəm. Bundan əlavə bildiyiniz hər hansı
almanca və rusca tutorial qaynaqlar varsa paylaşa bilərsiz. Əvvəlcədən
təşəkkürlər)

**Comment by isbendiyarovanezrin** [comment]
Elə, məncə, ən yaxşısı verdiyim altıncı qaynaqdır.

**Comment by isbendiyarovanezrin** [comment]
**[Bu](https://www.javascripttutorial.net)** qaynaq da ola bilər.

**Comment by isbendiyarovanezrin** [comment]
[**Bu**](https://courses.wesbos.com/account/access/618f907341ee9b1bad8e0aa7) tapşırıqları işləyərək də öyrənə bilərsiniz.
