### ISSUE TITLE
JavaScript faylları "js" adlı qovluqda olmalıdır

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Tahir2022/PragmatechFoundationProject#19]
Qovluq adı mütləq "js" olmalı deyil, amma içində JavaScript faylları olduğu üçün JavaScript ilə bağlı bir ad olmalıdır. Yaxşı olardı ki, "js" olsun.

**Comment by Tahir2022** [comment]
Aydındır. Qısa zamanda həll edəcəm)
