### ISSUE TITLE
Commit mesajlarına fikir verin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Tahir2022/PragmatechFoundationProject#35]
**"///"** belə commit mesajı yazmaq düzgün deyil.

**Comment by Tahir2022** [comment]
Nəzrin, multiple pages’ də hər bir faylı bir folder’in içində yerləşdirmək
lazımdır? Bütün səhifələr üçün bir js faylından istifadə etmək olar?

**Comment by isbendiyarovanezrin** [comment]
Bütün səhifələr üçün onsuz da 1 JavaScript faylından istifadə olunur.

**Comment by isbendiyarovanezrin** [comment]
Birinci sualda söhbət hansı fayllardan gedir? HTML?

**Comment by Tahir2022** [comment]
Bəs əgər HTMI’də adlandırmalar eyni olsa və ya tag’ lara js seçəndə problem
yaranmaz?

HTML&Css fayllarını nəzərdə tuturam. Yəni hər ikisi.

**Comment by isbendiyarovanezrin** [comment]
Yaratmayacaq şəkildə adlandırma edin və JavaScriptdə də o şəkildə çağırın.

**Comment by isbendiyarovanezrin** [comment]
CSS faylları təbii ki, bir qovluqda yazılır, HTML isə yox (qovluqda yazılmır).
