### ISSUE TITLE
Bəzi xırda səhvlər

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Tahir2022/PragmatechFoundationProject#6]
[İşarələdiyim](https://github.com/Tahir2022/PragmatechFoundationProject/blob/master/ProjectFrontEnd/index%20(2).html#L14) hissəni yazmağa ehtiyac yoxdur, çünki ondan əvvəl `<header>` teqindən istifadə etmisiniz. Class'ı da  `<header>` teqinə verə bilərsiniz.

**Comment by Tahir2022** [comment]
header teqini ümumi olaraq saytın yuxarı hissəsi üçün istifadə etmişəm və onun içindəki hissələri də header, middle və footer-section'lara bölərək hər birini ayrılıqda section teqi içərisində yazmışam. Belə daha asan oldu. Diqqət göstərdiyiniz üçün təşəkkürlər))

**Comment by isbendiyarovanezrin** [comment]
Onda class adlarında dəyişiklik edə bilərsiniz. Məsələn, `<section class="footer-section">` bu koda baxanda bilinmir ki, header'in footer hissəsidir, ona görə də  `class="header-footer-section"` yazmaq daha yaxşı olar, məncə.

**Comment by isbendiyarovanezrin** [comment]
Onda class adlarını edə bilərsiniz. Məsələn, bu `<section class="footer-section">` koda baxanda bilinmir ki, header'in footer hissəsidir. Ona görə də  `class="header-footer-section"` yazmaq daha yaxşı olar, məncə.

**Comment by isbendiyarovanezrin** [comment]
Onda class adlarını dəyişə bilərsiniz. Məsələn, bu `<section class="footer-section">` koda baxanda bilinmir ki, header'in footer hissəsidir. Ona görə də  `class="header-footer-section"` yazmaq daha yaxşı olar, məncə.
